calculadora/urls.py
from django.urls import path

from . import views

app_name = 'calculadora'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('calcular', views.calcular, name='calcular'),
    
]

cilindro/urls.py
from django.urls import path

from . import views

app_name = 'cilindro'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('respuesta', views.respuesta, name='respuesta'),
    
]

encuesta/urls.py
from django.urls import path 

from . import views 

app_name = 'encuesta'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('enviar', views.enviar, name='enviar'),
    
]

lab02/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('cilindro/', include('cilindro.urls')),
    path('calculadora/', include('calculadora.urls')),
    path('encuesta/', include('encuesta.urls')),
    path('admin/', admin.site.urls),
]

calculadora/models.py
from django.db import models

# Create your models here.

cilindro/models.py
from django.db import models

# Create your models here.

encuesta/models.py
from django.db import models

# Create your models here.

calculadora/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        'titulo': "calculadora",
    }
    return render(request, 'calculadora/calculadora.html', context)

def calcular(request):
    if request.method == 'POST':
        num1 = request.POST.get('num1')
        num2 = request.POST.get('num2')
        operacion = request.POST.get('operacion')
        resultado = 0
        if operacion == 'suma':
            resultado = int(num1) + int(num2)
        elif operacion == 'resta':
            resultado = int(num1) - int(num2)
        elif operacion == 'multiplicacion':
            resultado = int(num1) * int(num2)
        mensaje_resultado = f"La {operacion} de {num1} + {num2} = {resultado}."
        return render(request, 'calculadora/resultado.html', {'mensaje_resultado': mensaje_resultado})
    else:
        return render(request, 'calculadora/calculadora.html')

cilindro/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        'titulo': "cilindro",
    }
    return render(request, 'cilindro/cilindro.html', context)

def respuesta(request):
    if request.method == 'POST':
        altura = float(request.POST.get('altura'))
        diametro = float(request.POST.get('diametro'))
        radio = diametro / 2
        volumen = round(3.14159 * radio**2 * altura, 2)
        return render(request, 'cilindro/cilindro.html', {'volumen': volumen})
    else:
        return render(request, 'cilindro/cilindro.html')

encuesta/views.py
from django.shortcuts import render

# Create your views here.
def index (request):
    context = {
        'titulo':"Formulario"
     }  
    return render(request, 'encuesta/formulario.html', context) 
def enviar(request):
    context = {
        'titulo' : "Respuesta",
        'nombre' : request.POST["nombre"],
        'clave' : request.POST["password"],
        'educacion' : request.POST["educacion"],
        'nacionalidad' : request.POST["nacionalidad"],
        'idiomas' : request.POST.getlist["idiomas"],
        'correo' : request.POST["email"],
        'website' : request.POST["sitioweb"],
    }
    return render(request, 'encuesta/respuesta.html', context)

calculadora/templates/calculadora/calculadora.html
<h2>Calculadora</h2>
<form action="{% url 'calculadora:calcular' %}" method="post">
    {% csrf_token %}
    Numero 1:
    <input type="number" name="num1"><br>
    Numero 2:
    <input type="number" name="num2"><br>
    Operación:
    <select name="operacion">
        <option value="suma">Suma</option>
        <option value="resta">Resta</option>
        <option value="multiplicacion">Multiplicacion</option>
    </select><br>
    <input type="submit" name="submit" value="Calcular">
</form>

calculadora/templates/calculadora/resultado.html
<h2>Resultado</h2>
<p>{{ mensaje_resultado }}</p>

cilindro/templates/cilindro/cilindro.html
<h2>Calculadora de Volumen de un Cilindro</h2>
<form action="{% url 'cilindro:respuesta' %}" method="post">
    {% csrf_token %}
    Introduzca el diametro en metros:
    <input type="number" name="diametro" step="0.01"><br>
    <br>
    Introduzca la altura en metros:
    <input type="number" name="altura" step="0.01"><br>
    <br>
    <input type="submit" name="submit" value="calcular">
</form>
{% if volumen %}
<p>El volumen del cilindro es de {{ volumen }} metros cubicos.</p>
{% endif %}

encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'encuesta:enviar' %}" method="post">
    {% csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br>
    Contraseña:
    <input type="password" name="contraseña"><br>
    Educacion:
    <select name="educacion">
        <option value="sin-estudios">Sin estudios</option>
        <option value="educacion-obligatoria" selected="selected">Educacoin obligatoria</option>
        <option value="formacion-profesional">Formacion profesional</option>
        <option value="universidad">Universidad</option>
    </select><br>
    Nacionalidad:
    <input type="radio" name="nacionalidad" value="hispana">Hispana</input>
    <input type="radio" name="nacionalidad" value="otra">Otra</input><br>
    Idiomas:
    <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
    <input type="checkbox" name="idiomas" value="ingles">Ingles</input>
    <input type="checkbox" name="idiomas" value="frances">Frances</input>
    <input type="checkbox" name="idiomas" value="aleman">Aleman</input><br>
    Email:
    <input type="text" name="email"><br>
    Sitio web:
    <input type="text" name="sitioweb"><br>
    // Boton enviar
    <input type="submit" name="submit" value="Enviar">
</form>

encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo }}</h2>
<p>Nombre: {{ nombre }}</p>
<p>Clave: {{ clave }}</p>
<p>Educacion: {{ educacion }}</p>
<p>Nacionalidad: {{ nacionalidad }}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
<p>Email:{{ correo }}</p>
<p>Sitio Web:{{ website }}</p>